# Generated by Django 4.0.4 on 2022-04-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='trip',
            name='title',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default=True, max_length=300),
        ),
    ]
