# Generated by Django 4.0.4 on 2022-04-25 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comment_user_alter_log_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_commented',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
