# Generated by Django 4.0.4 on 2022-04-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment_date_commented'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
