# Generated by Django 4.0.4 on 2022-04-26 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_log_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='duration',
        ),
        migrations.AddField(
            model_name='log',
            name='date_logged',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='begin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
