# Generated by Django 4.0.4 on 2022-04-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_traveler'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='audience',
            field=models.CharField(blank=True, choices=[('friends', 'friends'), ('family', 'family'), ('public', 'public'), ('private', 'private')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='followers',
            field=models.ManyToManyField(related_name='trip_followers', to='core.contacts'),
        ),
    ]
