# Generated by Django 4.0.4 on 2022-04-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contacts_audience_trip_followers'),
        ('core', '0012_alter_image_picture'),
    ]

    operations = [
    ]
