# Generated by Django 4.0.4 on 2022-04-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20220428_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
