# Generated by Django 4.0.4 on 2022-04-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_comment_reactions_log_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='location',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
