# Generated by Django 4.0.4 on 2022-05-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_trip_begin_alter_trip_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(default='User has yet to fill in their bio', max_length=300),
        ),
    ]
