# Generated by Django 4.0.4 on 2022-05-03 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='start',
        ),
    ]
