# Generated by Django 4.0.4 on 2022-05-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='traveler',
        ),
        migrations.AddField(
            model_name='trip',
            name='subscribers',
            field=models.ManyToManyField(related_name='trip_subscribers', to='core.contacts'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
