# Generated by Django 4.0.4 on 2022-05-04 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_image_log_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='log_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_images', to='core.log'),
        ),
    ]
