# Generated by Django 4.0.4 on 2022-05-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_trip_followers_remove_user_traveler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='title',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.CharField(default='My Fantastic Getaway', max_length=200),
        ),
    ]
