# Generated by Django 4.0.4 on 2022-05-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_log_title_alter_trip_title'),
        ('core', '0028_remove_image_log_image_image_log'),
    ]

    operations = [
    ]
