# Generated by Django 4.0.4 on 2022-05-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_trip_subscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
