# Generated by Django 4.0.4 on 2022-05-04 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_contacts_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=75)),
                ('audience', models.CharField(blank=True, choices=[('friends', 'friends'), ('family', 'family'), ('public', 'public'), ('private', 'private')], max_length=30, null=True)),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='trip',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='trip_subscribers', to='core.contacts'),
        ),
    ]
