# Generated by Django 4.0.4 on 2022-05-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_image_log_image'),
        ('core', '0033_contacts_delete_contact_alter_trip_subscribers'),
    ]

    operations = [
    ]
