# Generated by Django 4.0.4 on 2022-05-04 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_merge_20220504_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='log_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_images', to='core.log'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='subscribers',
            field=models.ManyToManyField(related_name='trip_subscribers', to='core.contacts'),
        ),
    ]
