# Generated by Django 4.0.4 on 2022-05-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_image_log_image_alter_trip_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='trip_subscribers', to='core.contacts'),
        ),
    ]
