# Generated by Django 4.0.4 on 2022-05-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_image_log_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
